### ISSUE TITLE
"Bad Request (400)" when accessing the container

### ISSUE THREAD

**Issue by darenasc** [dssg/appy-reviews#55]
hi, I got issues trying to test the repository locally. After successful steps 1 and 2 of the installation instructions from the README I run `manage build`  on the terminal with no extra configuration and it creates two docker images `dsapp/appy-reviews/web` and `093198349272.dkr.ecr.us-west-2.amazonaws.com/dsapp/appy-reviews/web` which are identical. Then I run:

`docker run -itd -p 8000:8000 dsapp/appy-reviews/web`

And I got a **Bad Request (400)** message when I access `http://localhost:8000` and no response from the IP of the container and port 8000.

Is there something I'm missing during the installation? I'm using macOS 10.14.3 and I had to use `pyenv virtualenv 3.7.1 appy` because 3.7.2 wasn't available. Thank you.

**Comment by jesteria** [comment]
Hi @darenasc, we can chat about your development environment via another channel :+1:

**Comment by jesteria** [comment]
(In short, `localhost` is an unacceptable `Host:` header, unless you're running in development mode. And, that's only one of many reasons to run locally in development mode. Development mode can be triggered with the environment variable `APPY_DEBUG=[1|y|yes|t|true]`. And that and several other settings are built into the management command: `develop`.)
